# Generated by Django 5.1.3 on 2024-11-11 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                ("telegram_id", models.IntegerField(primary_key=True, serialize=False)),
                ("balance", models.DecimalField(decimal_places=10, max_digits=10)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "referral_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user_core.telegramuser",
                    ),
                ),
            ],
            options={
                "db_table": "telegram_user",
                "ordering": ["telegram_id"],
            },
        ),
    ]
