# Generated by Django 5.1.3 on 2024-11-11 18:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="telegramuser",
            old_name="referral_id",
            new_name="referral",
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="referral_token",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="balance",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
    ]
