# Generated by Django 5.1.3 on 2024-11-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_core", "0002_rename_referral_id_telegramuser_referral_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramuser",
            name="balance",
            field=models.IntegerField(default=0),
        ),
    ]
