# Generated by Django 5.1.3 on 2025-01-15 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_core", "0003_alter_telegramuser_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.SmallIntegerField(default=0)),
                ("feedback", models.TextField(blank=True, null=True)),
                ("conversation", models.TextField(blank=True, null=True)),
                (
                    "tg_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user_core.telegramuser",
                    ),
                ),
            ],
            options={
                "db_table": "telegram_chat",
                "ordering": ["tg_user", "id"],
            },
        ),
    ]
