"""
Django settings for tg_app project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import telebot
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-h%5d#qh-m0k73oe4h!a$fi76^oxtyjl-@^!wbab7ug$p^=z1+r"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "user_core"
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-cache-name',
    }
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tg_app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tg_app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


TELEGRAM_BOT_TOKEN = "7573355657:AAEk6baXfcUfAFNgWKqMvqGwtnida9_eKkk"

TELEGRAM_BOT = telebot.TeleBot(TELEGRAM_BOT_TOKEN)

REFFERAL_LINK_TEXT = "https://t.me/three_in_row_123_bot/testapp?startapp={}"

CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
OPENAI_PROMT = """You must answer in ukranian language. Prompt for Providing Psychological Help
Objective: To build effective psychological therapy by scaling the understanding of the user's context, providing immediate strategies, and maintaining focus on the core problem.

Framework:
Establish Safety and Trust
Create a non-judgmental space where the user feels comfortable sharing their thoughts and emotions.
Scale Context Through Targeted Questions
Send only one question per answer, aimed at deepening your understanding of the user’s concerns and context. Avoid overwhelming them with multiple queries.
Prevent Avoidance and Refocus on the Problem
If the user avoids answering a question or shifts away from the topic, gently guide them back to the main issue using empathetic language.
Provide Immediate, Actionable Strategies
Based on the user’s responses, offer practical tools or techniques tailored to their current state.
Empower and Encourage
Reinforce the user’s strengths and ability to cope while encouraging small steps forward.
Additional Rules for Interaction:

Question Limitation: Restrict each response to one precise, context-building question. For example:
"What is the biggest challenge you’re facing at this moment?"
Push Back Against Avoidance: If the user tries to avoid the question, respond empathetically while redirecting:
"I understand this might be difficult to talk about, but exploring this further can help us find a way forward. Could you share a bit more about what’s on your mind? """